### ISSUE TITLE
about pre_trained model

### ISSUE THREAD

**Issue by yyzyyzz** [GeoffreyChen777/DDT#1]
when I download the vgg19 model and prepared to load the model to vgg19, the code shows 'Source unavailable', what should I do?

**Comment by GeoffreyChen777** [comment]
@yyzyyzz Can you provide all the error outputs?

**Comment by yyzyyzz** [comment]
@GeoffreyChen777  Sorry, it's my fault, the model can be used, just the display window can't display the model parameters.
By the way, can I speed up by adding cuda?

**Comment by GeoffreyChen777** [comment]
You can use .cuda() to move the VGG and input image to GPU.

**Comment by GeoffreyChen777** [comment]
Close, feel free to reopen it if you have any questions.

**Comment by IsaacKam** [comment]
Hi Geoffrey again, just another quick question :), where exactly would I need to add `.cuda() ` to make it GPU compatible?

**Comment by GeoffreyChen777** [comment]
> Hi Geoffrey again, just another quick question :), where exactly would I need to add `.cuda() ` to make it GPU compatible?

https://github.com/GeoffreyChen777/DDT/blob/33efe8a304c219fea8ae8ad7c8fd1bbf5733918b/ddt.py#L21

=>
```
model = vgg19(pretrained=True).cuda()
```

https://github.com/GeoffreyChen777/DDT/blob/33efe8a304c219fea8ae8ad7c8fd1bbf5733918b/ddt.py#L29
=>
```
imgs = torch.cat(imgs).cuda()
```
