### ISSUE TITLE
Size mismatch when swapping vgg19 for smaller models.

### ISSUE THREAD

**Issue by IsaacKam** [GeoffreyChen777/DDT#2]
I have replaced vgg19 with vgg11 in DDT.py  like this:
`model = vgg11(pretrained=True)`

and receive the following error when I run it:
`RuntimeError: size mismatch, m1: [6 x 4608], m2: [25088 x 4096] at /Users/soumith/mc3build/conda-bld/pytorch_1549312653646/work/aten/src/TH/generic/THTensorMath.cpp:940`

I was wondering how would I make it work for smaller faster models?

**Comment by GeoffreyChen777** [comment]
This error caused by the classifier in VGG:
https://github.com/GeoffreyChen777/DDT/blob/33efe8a304c219fea8ae8ad7c8fd1bbf5733918b/vgg.py#L30
https://github.com/GeoffreyChen777/DDT/blob/33efe8a304c219fea8ae8ad7c8fd1bbf5733918b/vgg.py#L46
 In DDT, the classifier is useless. You can remove it.

**Comment by IsaacKam** [comment]
Thank you :)
