### ISSUE TITLE
how to discovery Unsupervised object?

### ISSUE THREAD

**Issue by ake020675** [GeoffreyChen777/DDT#3]
This project seems to generate CNN saliency map of the input image.
The dataset and code here are not available now:
http://www.lamda.nju.edu.cn/weixs/project/DDT/DDT.html
Do u have them and can u share?

**Comment by GeoffreyChen777** [comment]
@ake020675 Hi, I'm not the author of this paper. This repo is my implementation of DDT. You should contact the original authors for the dataset issue.
